version: "3"

services:
  web:
  browser:
    image: g105b/chromium-headless
    command: "http://localhost"
  test:
    image: php:7.3-cli
    volumes:
     - "./:/app"
    working_dir: /app
    command: vendor/bin/behat